apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
# name can be inferred from the filename or from the for resource
spec: 
  for: 
    group: infra.kuid.dev
    version: v1alpha1
    kind: Node
    selector: {}
  owns:
  - group: ipam.be.kuid.dev
    version: v1alpha1
    kind: IPClaim
  watches:
  - group: ipam.be.kuid.dev
    version: v1alpha1
    kind: IPIndex
    selector:
      match:
        metadata.name: kubenet.default
        status.conditions.exists(c, c.type == 'Ready' && c.status == 'True'): "true"
