apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
metadata:
  annotations:
    api.choreo.kform.dev/origin: '{"kind":"File"}'
  creationTimestamp: null
  name: device.kubenet.dev.subinterfaces.config.nokiasrl
spec:
  code:
    main.jinja2: "{%- import 'subinterface.jinja2' subinterface -%}\napiVersion: config.sdcio.dev/v1alpha1\nkind:
      Config\nmetadata:\n  name: {{ metadata.name }}\n  namespace: {{ metadata.namespace
      }}\n  labels:\n    config.sdcio.dev/targetName: {{ spec.node }}\n    config.sdcio.dev/targetNamespace:
      {{ metadata.namespace }}\n  ownerReferences:\n  - apiVersion: {{ apiVersion
      }}\n    controller: true\n    kind: {{ kind }}\n    name: {{ metadata.name }}\n
      \   uid: {{ metadata.uid }}\nspec:\n  priority: 10\n  config:\n  - path: /\n
      \   value: \n      {{ subinterface(spec) -}} "
    subinterface.jinja2: |-
      {%- macro subinterface(spec) export -%}
            interface:
            - name: {{ spec.name }}
              subinterface:
              - index: {{ spec.id }}
                type: {{ spec.type }}
                description: k8s-{{ spec.name }}.{{ spec.id }}
                admin-state: enable
           {%- if spec.ipv4 %}
                ipv4:
                  admin-state: enable
              {%- if spec.ipv4.addresses|length > 0 %}
                  address:
              {%- for address in spec.ipv4.addresses %}
                  - ip-prefix: {{ address }}
              {%- endfor %}
                  unnumbered:
                    admin-state: disable
              {%- endif %}
           {%- endif %}
           {%- if spec.ipv6 %}
                ipv6:
                  admin-state: enable
                  router-advertosement:
                    router-role:
                      admin-state: enable
              {%- if spec.ipv6.addresses|length > 0 %}
                  address:
              {%- for address in spec.ipv6.addresses %}
                  - ip-prefix: {{ address }}
              {%- endfor %}
              {%- endif %}
           {%- endif %}
      {%- endmacro %}
  for:
    group: device.network.kubenet.dev
    kind: SubInterface
    selector: {}
    version: v1alpha1
  owns:
  - group: config.sdcio.dev
    kind: Config
    version: v1alpha1
  type: jinjatemplate
status: {}
