apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
metadata:
  annotations:
    api.choreo.kform.dev/origin: '{"kind":"File"}'
  creationTimestamp: null
  name: device.kubenet.dev.interfaces.config.nokiasrl
spec:
  code:
    interface.jinja2: |-
      {%- macro interface(spec) export -%}
            interface:
            - name: {{ spec.name }}
              description: k8s-{{ spec.name }}
              admin-state: enable
          {%- if spec.vlanTagging %}
              vlan-tagging: true
          {%- endif %}
      {%- endmacro %}
    main.jinja2: "{%- import 'interface.jinja2' interface -%}\napiVersion: config.sdcio.dev/v1alpha1\nkind:
      Config\nmetadata:\n  name: {{ metadata.name }}\n  namespace: {{ metadata.namespace
      }}\n  labels:\n    config.sdcio.dev/targetName: {{ spec.node }}\n    config.sdcio.dev/targetNamespace:
      {{ metadata.namespace }}\n  ownerReferences:\n  - apiVersion: {{ apiVersion
      }}\n    controller: true\n    kind: {{ kind }}\n    name: {{ metadata.name }}\n
      \   uid: {{ metadata.uid }}\nspec:\n  priority: 10\n  config:\n  - path: /\n
      \   value: \n      {{ interface(spec) -}} \n"
  for:
    group: device.network.kubenet.dev
    kind: Interface
    selector: {}
    version: v1alpha1
  owns:
  - group: config.sdcio.dev
    kind: Config
    version: v1alpha1
  type: jinjatemplate
status: {}
