apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
# name can be inferred from the filename or from the for resource
spec: 
  for: 
    group: device.network.kubenet.dev
    version: v1alpha1
    kind: Interface
    selector: {}
  owns:
  - group: config.sdcio.dev
    version: v1alpha1
    kind: Config
