apiVersion: ipam.be.kuid.dev/v1alpha1
kind: IPIndex
metadata:
  name: kubenet.default
  namespace: default
spec:
  prefixes:
  - prefix: 10.0.0.0/24
    prefixType: pool
    labels:
      infra.kuid.dev/purpose: loopback
  - prefix: 1000::/32
    prefixType: pool
    labels:
      infra.kuid.dev/purpose: loopback