apiVersion: choreo.kform.dev/v1alpha1
kind: Library
metadata:
  annotations:
    api.choreo.kform.dev/origin: '{"kind":"File"}'
  creationTimestamp: "2024-10-01T07:10:05Z"
  managedFields:
  - apiVersion: choreo.kform.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:api.choreo.kform.dev/origin: {}
      f:spec:
        .: {}
        f:code: {}
        f:type: {}
      f:status: {}
    manager: inputfileloader
    operation: Apply
    time: "2024-10-01T07:10:05Z"
  name: example.com.greetings.star
  resourceVersion: "0"
  uid: 4f636582-983e-404e-ba0f-a9e8b9aaf301
spec:
  code: |-
    load("api.k8s.io.object.star", "getName", "getNamespace", "getSpec")

    def getGreeting(self, msg):
      return {
        "apiVersion": "example.com/v1alpha1",
        "kind": "Greeting",
        "metadata": {
            "name": getName(self),
            "namespace": getNamespace(self),
        },
        "spec": {
          "message": getGreetingMsg(self, msg)
        },
      }

    def getGreetingMsg(self, msg):
      spec = getSpec(self)
      return spec.get("greeting", msg)
  type: starlark
status: {}
